### ISSUE TITLE
What if I want to add location marker at ground level.

### ISSUE THREAD

**Issue by kambojumang** [CoreBuildSoftware/android-arcore#1]
Hello All, 

Great work, I want to know how can we add a location marker on ground level as per the sea level. Like If landscape or location is on first floor or second floor how we can distinguish them. 

Thanks,
Umang Kamboj

**Comment by todoranalex** [comment]
Hello,

I think one way to achieve this would be to compute the phone's altitude and also the marker's location altitude. The difference between those should let you decide whether you need to raise or lower your marker's position. But remember, the altitudes are always relative to the sea level. And this may lead to undesired results.
